// <auto-generated />
namespace SP_ASPNET_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editBlogPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editBlogPost));
        
        string IMigrationMetadata.Id
        {
            get { return "202007111309244_editBlogPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
